server:
  port: 8086
spring:
  application:
    name: hzero_platform
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://39.101.202.67:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false}
    username: ${SPRING_DATASOURCE_USERNAME:super}
    password: ${SPRING_DATASOURCE_PASSWORD:super@123}
  security:
    user:
      name: super
      password: super@123
  redis:
    database: 0
    host: 39.101.202.67
    port: 6379
    password:
    timeout: 20000        # 连接超时时间（毫秒）
    pool:
      max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 20000     # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8         # 连接池中的最大空闲连接
      min-idle: 0         # 连接池中的最小空闲连接


mybatis:
  mapperLocations:
    - classpath*:/mapper/*Mapper.xml
    - classpath*:/mapper/*/*Mapper.xml


